apiVersion: discovery.knative.dev/v1alpha1
kind: DuckType
metadata:
  name: addressable.duck.knative.dev
spec:
  selectors:
    - selector: "duck.knative.dev/addressable=true"

  refs:
    - version: v1
      resource: services
      kind: Service

  names:
    plural: addressables
    singular: addressable

  additionalPrinterColumns:
    - name: Ready
      type: string
      JSONPath: ".status.conditions[?(@.type=='Ready')].status"
    - name: Reason
      type: string
      JSONPath: ".status.conditions[?(@.type=='Ready')].reason"
    - name: URL
      type: string
      JSONPath: .status.address.url
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp

  schema:
    openAPIV3Schema:
      properties:
        status:
          type: object
          properties:
            address:
              type: object
              properties:
                url:
                  type: string